# ==============================
# Deployment
# ==============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: realworld-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: us-east1-docker.pkg.dev/test-12625323/gke-microservice/api-gateway:2
        ports:
        - containerPort: 8085

        env:
        - name: USER_SERVICE_URL
          value: http://user-service:8081
        - name: ORDER_SERVICE_URL
          value: http://order-service:8082
        - name: CATALOG_SERVICE_URL
          value: http://catalog-service:8083

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 5

        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8085
          initialDelaySeconds: 60
          periodSeconds: 20
          failureThreshold: 3
          timeoutSeconds: 5

---

# ==============================
# Service (ClusterIP)
# ==============================
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: realworld-prod
  annotations:
    cloud.google.com/backend-config: '{"ports": {"http":"api-gateway-backendconfig"}}'
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8085

---

# ==============================
# BackendConfig (GKE health check)
# ==============================
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-backendconfig
  namespace: realworld-prod
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    requestPath: /actuator/health
    port: 80
    type: HTTP