apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: us-east1-docker.pkg.dev/test-12625323/gke-microservice/order-service:3
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql:3306/appdb
        - name: SPRING_DATASOURCE_USERNAME
          value: appuser
        - name: SPRING_DATASOURCE_PASSWORD
          value: apppass
        - name: USER_SERVICE_URL
          value: http://user-service:8081
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8082
      targetPort: 8082
